### ISSUE TITLE
部分疑问，求解答（半解决

### ISSUE THREAD

**Issue by SupersuROOT** [xtuiflyzhkt/iflytek_cyzhkt_cr#6]
请问
既然管控平台、学生桌面等都是通过MDM权限对学生平板进行控制、搜集信息，那么

- 是不是可以通过修改apk禁用权限的方法使管控平台等应用不再搜集信息？如果可以，具体需要修改哪些权限？
- 是不是可以通过修改apk禁用权限的方法是学生平板脱离控制？如果可以，具体需要修改哪些权限？

我们使用的是`X1 PRO`，但平板内的内置软件于该项目中的一致，所以恳请大佬解答

`(ps:我才刚刚开始研究这个平板，目前可以进9008修改系统了，所以才想请教大佬一下`

**Comment by xtuiflyzhkt** [comment]
修改apk会导致校验失败

**Comment by SupersuROOT** [comment]
> 修改apk会导致校验失败

感谢提醒，经实验我们这个平板可以暂时root并在除课堂版之外的系统安装课堂应用（不过目前没有时间去测试了
感谢大佬提供的破解思路

**Comment by SupersuROOT** [comment]
已测试可以root，但部分课堂版应用在装完后会闪退（比如中学生作业HD）
并且X1PRO的桌面会缺失AI学
这些问题留到之后再问

**Comment by worryzu** [comment]
> 请问 既然管控平台、学生桌面等都是通过MDM权限对学生平板进行控制、搜集信息，那么
> 
> * 是不是可以通过修改apk禁用权限的方法使管控平台等应用不再搜集信息？如果可以，具体需要修改哪些权限？
> * 是不是可以通过修改apk禁用权限的方法是学生平板脱离控制？如果可以，具体需要修改哪些权限？
> 
> 我们使用的是`X1 PRO`，但平板内的内置软件于该项目中的一致，所以恳请大佬解答
> 
> `(ps:我才刚刚开始研究这个平板，目前可以进9008修改系统了，所以才想请教大佬一下`

不可以，会导致管控平台无法确定，但是5.0.qlsj貌似可以改

**Comment by misane-k** [comment]
我对管控原理感兴趣，请问还在研究管控平台吗？可以私聊我吗？@worryzu
